import {
  StaffAccount,
  PharmacyDrugItem,
  MedicalServiceItem,
  DoctorSchedule,
} from '../models/admin.model';

export const MOCK_STAFF_ACCOUNTS: StaffAccount[] = [
  {
    id: 'STAFF-01',
    username: 'hoang.tran',
    fullName: 'TS.BS Trần Minh Hoàng',
    email: 'hoang.tran@smartclinic.vn',
    phone: '0912 345 678',
    role: 'DOCTOR',
    department: 'Khoa Tim Mạch',
    title: 'Bác sĩ Chuyên khoa II - Trưởng khoa',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-06 07:30',
    createdAt: '2024-01-15',
  },
  {
    id: 'STAFF-02',
    username: 'mai.lan',
    fullName: 'ThS.BS Nguyễn Thị Mai Lan',
    email: 'lan.nguyen@smartclinic.vn',
    phone: '0908 112 233',
    role: 'DOCTOR',
    department: 'Khoa Nội Tổng Quát',
    title: 'Thạc sĩ Bác sĩ Nội trú',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-05 13:45',
    createdAt: '2024-03-20',
  },
  {
    id: 'STAFF-03',
    username: 'hung.le',
    fullName: 'BS.CKI Lê Quốc Hưng',
    email: 'hung.le@smartclinic.vn',
    phone: '0934 556 677',
    role: 'DOCTOR',
    department: 'Khoa Tiêu Hóa',
    title: 'Bác sĩ CKI Tiêu hóa - Gan mật',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-05 08:15',
    createdAt: '2024-05-10',
  },
  {
    id: 'STAFF-04',
    username: 'mai.nguyen',
    fullName: 'Nguyễn Thị Mai',
    email: 'mai.nguyen@smartclinic.vn',
    phone: '0903 123 456',
    role: 'RECEPTIONIST',
    department: 'Quầy Tiếp Đón & Thu Ngân',
    title: 'Trưởng nhóm Lễ tân & Thu ngân',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-06 07:00',
    createdAt: '2024-02-01',
  },
  {
    id: 'STAFF-05',
    username: 'huong.pham',
    fullName: 'Phạm Thu Hương',
    email: 'huong.pham@smartclinic.vn',
    phone: '0978 998 877',
    role: 'RECEPTIONIST',
    department: 'Quầy Tiếp Đón & Thu Ngân',
    title: 'Nhân viên Tiếp đón bệnh nhân',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-05 17:00',
    createdAt: '2024-06-15',
  },
  {
    id: 'STAFF-06',
    username: 'son.le',
    fullName: 'Lê Hoàng Sơn',
    email: 'son.le@smartclinic.vn',
    phone: '0988 777 666',
    role: 'ADMIN',
    department: 'Ban Giám Đốc & CNTT',
    title: 'Giám đốc Vận hành & Quản trị Hệ thống',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-06 08:00',
    createdAt: '2023-11-01',
  },
  {
    id: 'STAFF-07',
    username: 'duy.tran',
    fullName: 'Trần Quốc Duy',
    email: 'duy.tran@smartclinic.vn',
    phone: '0945 332 211',
    role: 'RECEPTIONIST',
    department: 'Quầy Tiếp Đón',
    title: 'Nhân viên Lễ tân (Tạm khóa)',
    status: 'LOCKED',
    lastLoginAt: '2026-09-20 11:30',
    createdAt: '2024-04-12',
  },
];

export const MOCK_PHARMACY_DRUGS: PharmacyDrugItem[] = [
  {
    id: 'DRUG-01',
    code: 'AUG1G',
    name: 'Augmentin 1g',
    activeIngredient: 'Amoxicillin + Clavulanic Acid',
    strength: '875mg/125mg',
    unit: 'Hộp 14 viên',
    importPrice: 165000,
    salePrice: 195000,
    stockQuantity: 4, // CRITICAL <= 10
    minAlertThreshold: 10,
    batchNumber: 'AG-2025-09',
    expiryDate: '2027-06-30',
    manufacturer: 'GlaxoSmithKline (Pháp)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-02',
    code: 'PAN500',
    name: 'Panadol Extra',
    activeIngredient: 'Paracetamol + Caffeine',
    strength: '500mg/65mg',
    unit: 'Hộp 15 vỉ',
    importPrice: 120000,
    salePrice: 145000,
    stockQuantity: 7, // CRITICAL <= 10
    minAlertThreshold: 10,
    batchNumber: 'PD-2026-01',
    expiryDate: '2028-01-15',
    manufacturer: 'Sanofi (Việt Nam)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-03',
    code: 'NEX40',
    name: 'Nexium 40mg',
    activeIngredient: 'Esomeprazole',
    strength: '40mg',
    unit: 'Hộp 28 viên',
    importPrice: 320000,
    salePrice: 380000,
    stockQuantity: 9, // CRITICAL <= 10
    minAlertThreshold: 10,
    batchNumber: 'NX-2025-11',
    expiryDate: '2027-11-20',
    manufacturer: 'AstraZeneca (Thụy Điển)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-04',
    code: 'AML05',
    name: 'Amlor 5mg',
    activeIngredient: 'Amlodipine Besylate',
    strength: '5mg',
    unit: 'Hộp 30 viên',
    importPrice: 180000,
    salePrice: 220000,
    stockQuantity: 24, // LOW <= 30
    minAlertThreshold: 10,
    batchNumber: 'AM-2025-04',
    expiryDate: '2027-08-10',
    manufacturer: 'Pfizer (Mỹ)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-05',
    code: 'GLU850',
    name: 'Glucophage 850mg',
    activeIngredient: 'Metformin Hydrochloride',
    strength: '850mg',
    unit: 'Hộp 50 viên',
    importPrice: 110000,
    salePrice: 135000,
    stockQuantity: 45, // GOOD
    minAlertThreshold: 10,
    batchNumber: 'GL-2025-10',
    expiryDate: '2027-12-05',
    manufacturer: 'Merck Santé (Đức)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-06',
    code: 'PLA75',
    name: 'Plavix 75mg',
    activeIngredient: 'Clopidogrel',
    strength: '75mg',
    unit: 'Hộp 30 viên',
    importPrice: 450000,
    salePrice: 530000,
    stockQuantity: 18, // LOW
    minAlertThreshold: 10,
    batchNumber: 'PL-2025-08',
    expiryDate: '2027-05-25',
    manufacturer: 'Sanofi Winthrop (Pháp)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-07',
    code: 'ASP81',
    name: 'Aspirin pH8',
    activeIngredient: 'Aspirin',
    strength: '100mg',
    unit: 'Hộp 100 viên',
    importPrice: 85000,
    salePrice: 110000,
    stockQuantity: 62, // GOOD
    minAlertThreshold: 10,
    batchNumber: 'AS-2025-12',
    expiryDate: '2028-02-18',
    manufacturer: 'Stella Pharm (Việt Nam)',
    status: 'ACTIVE',
  },
  {
    id: 'DRUG-08',
    code: 'SIM10',
    name: 'Zocor 10mg (Ngừng kinh doanh)',
    activeIngredient: 'Simvastatin',
    strength: '10mg',
    unit: 'Hộp 30 viên',
    importPrice: 190000,
    salePrice: 230000,
    stockQuantity: 0,
    minAlertThreshold: 10,
    batchNumber: 'ZC-2024-01',
    expiryDate: '2025-12-31',
    manufacturer: 'MSD (Mỹ)',
    status: 'DISCONTINUED', // BR-21: Soft status change, not physically deleted
  },
];

export const MOCK_MEDICAL_SERVICES: MedicalServiceItem[] = [
  {
    id: 'MS-01',
    serviceCode: 'KB-TIMMACH',
    serviceName: 'Khám Chuyên Khoa Tim Mạch',
    category: 'KHÁM BỆNH',
    price: 200000,
    roomName: 'Phòng khám Nội 101',
    unit: 'Lượt',
    estimatedDurationMinutes: 20,
    isActive: true,
  },
  {
    id: 'MS-02',
    serviceCode: 'KB-NOITQ',
    serviceName: 'Khám Nội Tổng Quát Toàn Diện',
    category: 'KHÁM BỆNH',
    price: 150000,
    roomName: 'Phòng khám Nội 102',
    unit: 'Lượt',
    estimatedDurationMinutes: 15,
    isActive: true,
  },
  {
    id: 'MS-03',
    serviceCode: 'ECG-12C',
    serviceName: 'Điện tâm đồ vi tính 12 chuyển đạo (ECG)',
    category: 'CẬN LÂM SÀNG',
    price: 100000,
    roomName: 'Phòng Đo Điện Tim (ECG)',
    unit: 'Lần',
    estimatedDurationMinutes: 10,
    isActive: true,
  },
  {
    id: 'MS-04',
    serviceCode: 'US-BUNGTQ',
    serviceName: 'Siêu âm ổ bụng tổng quát màu Doppler',
    category: 'CHẨN ĐOÁN HÌNH ẢNH',
    price: 250000,
    roomName: 'Phòng Siêu Âm 01',
    unit: 'Lần',
    estimatedDurationMinutes: 15,
    isActive: true,
  },
  {
    id: 'MS-05',
    serviceCode: 'XR-NGUC',
    serviceName: 'X-quang ngực thẳng kỹ thuật số (DR)',
    category: 'CHẨN ĐOÁN HÌNH ẢNH',
    price: 150000,
    roomName: 'Phòng X-Quang Kỹ Thuật Số',
    unit: 'Lần',
    estimatedDurationMinutes: 10,
    isActive: true,
  },
  {
    id: 'MS-06',
    serviceCode: 'XN-CBC24',
    serviceName: 'Tổng phân tích tế bào máu ngoại vi (CBC 24 thông số)',
    category: 'XÉT NGHIỆM',
    price: 120000,
    roomName: 'Phòng Xét Nghiệm Trung Tâm',
    unit: 'Mẫu',
    estimatedDurationMinutes: 30,
    isActive: true,
  },
  {
    id: 'MS-07',
    serviceCode: 'XN-LIPID',
    serviceName: 'Bộ mỡ máu toàn phần (Cholesterol, Triglyceride, HDL, LDL)',
    category: 'XÉT NGHIỆM',
    price: 200000,
    roomName: 'Phòng Xét Nghiệm Trung Tâm',
    unit: 'Mẫu',
    estimatedDurationMinutes: 45,
    isActive: true,
  },
  {
    id: 'MS-08',
    serviceCode: 'XN-GLUCOSE',
    serviceName: 'Định lượng Glucose máu tĩnh mạch',
    category: 'XÉT NGHIỆM',
    price: 50000,
    roomName: 'Phòng Xét Nghiệm Trung Tâm',
    unit: 'Mẫu',
    estimatedDurationMinutes: 20,
    isActive: true,
  },
];

export const MOCK_DOCTOR_SCHEDULES: DoctorSchedule[] = [
  {
    id: 'SCH-01',
    doctorId: 'STAFF-01',
    doctorName: 'TS.BS Trần Minh Hoàng',
    specialty: 'Tim Mạch',
    roomName: 'Phòng khám Nội 101',
    date: '2026-10-06',
    shift: 'MORNING',
    status: 'CONFIRMED',
    maxPatients: 25,
    bookedPatients: 18,
  },
  {
    id: 'SCH-02',
    doctorId: 'STAFF-01',
    doctorName: 'TS.BS Trần Minh Hoàng',
    specialty: 'Tim Mạch',
    roomName: 'Phòng khám Nội 101',
    date: '2026-10-06',
    shift: 'AFTERNOON',
    status: 'CONFIRMED',
    maxPatients: 20,
    bookedPatients: 12,
  },
  {
    id: 'SCH-03',
    doctorId: 'STAFF-02',
    doctorName: 'ThS.BS Nguyễn Thị Mai Lan',
    specialty: 'Nội Tổng Quát',
    roomName: 'Phòng khám Nội 102',
    date: '2026-10-06',
    shift: 'MORNING',
    status: 'CONFIRMED',
    maxPatients: 30,
    bookedPatients: 24,
  },
  {
    id: 'SCH-04',
    doctorId: 'STAFF-03',
    doctorName: 'BS.CKI Lê Quốc Hưng',
    specialty: 'Tiêu Hóa',
    roomName: 'Phòng khám Nội 103',
    date: '2026-10-06',
    shift: 'MORNING',
    status: 'CONFIRMED',
    maxPatients: 20,
    bookedPatients: 16,
  },
  {
    id: 'SCH-05',
    doctorId: 'STAFF-02',
    doctorName: 'ThS.BS Nguyễn Thị Mai Lan',
    specialty: 'Nội Tổng Quát',
    roomName: 'Phòng khám Nội 102',
    date: '2026-10-07',
    shift: 'MORNING',
    status: 'CONFIRMED',
    maxPatients: 30,
    bookedPatients: 15,
  },
  {
    id: 'SCH-06',
    doctorId: 'STAFF-03',
    doctorName: 'BS.CKI Lê Quốc Hưng',
    specialty: 'Tiêu Hóa',
    roomName: 'Phòng khám Nội 103',
    date: '2026-10-07',
    shift: 'MORNING',
    status: 'LEAVE',
    maxPatients: 0,
    bookedPatients: 0,
  },
];
